// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book.proto

package page.janardhan.labs.protos;

public interface BookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:labs.Book)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 id = 2;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional int32 id = 2;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>optional int32 price = 3;</code>
   * @return Whether the price field is set.
   */
  boolean hasPrice();
  /**
   * <code>optional int32 price = 3;</code>
   * @return The price.
   */
  int getPrice();

  /**
   * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
   */
  java.util.List<page.janardhan.labs.protos.Book.GenreNumber> 
      getGenresList();
  /**
   * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
   */
  page.janardhan.labs.protos.Book.GenreNumber getGenres(int index);
  /**
   * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
   */
  int getGenresCount();
  /**
   * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
   */
  java.util.List<? extends page.janardhan.labs.protos.Book.GenreNumberOrBuilder> 
      getGenresOrBuilderList();
  /**
   * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
   */
  page.janardhan.labs.protos.Book.GenreNumberOrBuilder getGenresOrBuilder(
      int index);
}
