// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book.proto

package page.janardhan.labs.protos;

/**
 * Protobuf type {@code labs.Book}
 */
public final class Book extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:labs.Book)
    BookOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Book.newBuilder() to construct.
  private Book(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Book() {
    name_ = "";
    genres_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Book();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Book(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            name_ = bs;
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            id_ = input.readInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            price_ = input.readInt32();
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              genres_ = new java.util.ArrayList<page.janardhan.labs.protos.Book.GenreNumber>();
              mutable_bitField0_ |= 0x00000008;
            }
            genres_.add(
                input.readMessage(page.janardhan.labs.protos.Book.GenreNumber.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        genres_ = java.util.Collections.unmodifiableList(genres_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return page.janardhan.labs.protos.BookProtos.internal_static_labs_Book_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return page.janardhan.labs.protos.BookProtos.internal_static_labs_Book_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            page.janardhan.labs.protos.Book.class, page.janardhan.labs.protos.Book.Builder.class);
  }

  /**
   * <pre>
   * tag numbers 1-15 require one less byte to encode than higher
   * numbers, so as an optimization use these for commonly usedor
   * repeated elements.
   * </pre>
   *
   * Protobuf enum {@code labs.Book.GenreType}
   */
  public enum GenreType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FICTION = 0;</code>
     */
    FICTION(0),
    /**
     * <code>REALSTORY = 1;</code>
     */
    REALSTORY(1),
    /**
     * <code>EDUCATIONAL = 2;</code>
     */
    EDUCATIONAL(2),
    ;

    /**
     * <code>FICTION = 0;</code>
     */
    public static final int FICTION_VALUE = 0;
    /**
     * <code>REALSTORY = 1;</code>
     */
    public static final int REALSTORY_VALUE = 1;
    /**
     * <code>EDUCATIONAL = 2;</code>
     */
    public static final int EDUCATIONAL_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static GenreType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static GenreType forNumber(int value) {
      switch (value) {
        case 0: return FICTION;
        case 1: return REALSTORY;
        case 2: return EDUCATIONAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GenreType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GenreType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GenreType>() {
            public GenreType findValueByNumber(int number) {
              return GenreType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return page.janardhan.labs.protos.Book.getDescriptor().getEnumTypes().get(0);
    }

    private static final GenreType[] VALUES = values();

    public static GenreType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GenreType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:labs.Book.GenreType)
  }

  public interface GenreNumberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:labs.Book.GenreNumber)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string number = 1;</code>
     * @return Whether the number field is set.
     */
    boolean hasNumber();
    /**
     * <code>optional string number = 1;</code>
     * @return The number.
     */
    java.lang.String getNumber();
    /**
     * <code>optional string number = 1;</code>
     * @return The bytes for number.
     */
    com.google.protobuf.ByteString
        getNumberBytes();

    /**
     * <code>optional .labs.Book.GenreType type = 2 [default = FICTION];</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>optional .labs.Book.GenreType type = 2 [default = FICTION];</code>
     * @return The type.
     */
    page.janardhan.labs.protos.Book.GenreType getType();
  }
  /**
   * Protobuf type {@code labs.Book.GenreNumber}
   */
  public static final class GenreNumber extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:labs.Book.GenreNumber)
      GenreNumberOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GenreNumber.newBuilder() to construct.
    private GenreNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GenreNumber() {
      number_ = "";
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GenreNumber();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GenreNumber(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              number_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              page.janardhan.labs.protos.Book.GenreType value = page.janardhan.labs.protos.Book.GenreType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return page.janardhan.labs.protos.BookProtos.internal_static_labs_Book_GenreNumber_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return page.janardhan.labs.protos.BookProtos.internal_static_labs_Book_GenreNumber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              page.janardhan.labs.protos.Book.GenreNumber.class, page.janardhan.labs.protos.Book.GenreNumber.Builder.class);
    }

    private int bitField0_;
    public static final int NUMBER_FIELD_NUMBER = 1;
    private volatile java.lang.Object number_;
    /**
     * <code>optional string number = 1;</code>
     * @return Whether the number field is set.
     */
    @java.lang.Override
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string number = 1;</code>
     * @return The number.
     */
    @java.lang.Override
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          number_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string number = 1;</code>
     * @return The bytes for number.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>optional .labs.Book.GenreType type = 2 [default = FICTION];</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override public boolean hasType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .labs.Book.GenreType type = 2 [default = FICTION];</code>
     * @return The type.
     */
    @java.lang.Override public page.janardhan.labs.protos.Book.GenreType getType() {
      @SuppressWarnings("deprecation")
      page.janardhan.labs.protos.Book.GenreType result = page.janardhan.labs.protos.Book.GenreType.valueOf(type_);
      return result == null ? page.janardhan.labs.protos.Book.GenreType.FICTION : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof page.janardhan.labs.protos.Book.GenreNumber)) {
        return super.equals(obj);
      }
      page.janardhan.labs.protos.Book.GenreNumber other = (page.janardhan.labs.protos.Book.GenreNumber) obj;

      if (hasNumber() != other.hasNumber()) return false;
      if (hasNumber()) {
        if (!getNumber()
            .equals(other.getNumber())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (type_ != other.type_) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasNumber()) {
        hash = (37 * hash) + NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getNumber().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static page.janardhan.labs.protos.Book.GenreNumber parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static page.janardhan.labs.protos.Book.GenreNumber parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static page.janardhan.labs.protos.Book.GenreNumber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static page.janardhan.labs.protos.Book.GenreNumber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static page.janardhan.labs.protos.Book.GenreNumber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static page.janardhan.labs.protos.Book.GenreNumber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static page.janardhan.labs.protos.Book.GenreNumber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static page.janardhan.labs.protos.Book.GenreNumber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static page.janardhan.labs.protos.Book.GenreNumber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static page.janardhan.labs.protos.Book.GenreNumber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static page.janardhan.labs.protos.Book.GenreNumber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static page.janardhan.labs.protos.Book.GenreNumber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(page.janardhan.labs.protos.Book.GenreNumber prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code labs.Book.GenreNumber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:labs.Book.GenreNumber)
        page.janardhan.labs.protos.Book.GenreNumberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return page.janardhan.labs.protos.BookProtos.internal_static_labs_Book_GenreNumber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return page.janardhan.labs.protos.BookProtos.internal_static_labs_Book_GenreNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                page.janardhan.labs.protos.Book.GenreNumber.class, page.janardhan.labs.protos.Book.GenreNumber.Builder.class);
      }

      // Construct using page.janardhan.labs.protos.Book.GenreNumber.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        number_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return page.janardhan.labs.protos.BookProtos.internal_static_labs_Book_GenreNumber_descriptor;
      }

      @java.lang.Override
      public page.janardhan.labs.protos.Book.GenreNumber getDefaultInstanceForType() {
        return page.janardhan.labs.protos.Book.GenreNumber.getDefaultInstance();
      }

      @java.lang.Override
      public page.janardhan.labs.protos.Book.GenreNumber build() {
        page.janardhan.labs.protos.Book.GenreNumber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public page.janardhan.labs.protos.Book.GenreNumber buildPartial() {
        page.janardhan.labs.protos.Book.GenreNumber result = new page.janardhan.labs.protos.Book.GenreNumber(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.number_ = number_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof page.janardhan.labs.protos.Book.GenreNumber) {
          return mergeFrom((page.janardhan.labs.protos.Book.GenreNumber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(page.janardhan.labs.protos.Book.GenreNumber other) {
        if (other == page.janardhan.labs.protos.Book.GenreNumber.getDefaultInstance()) return this;
        if (other.hasNumber()) {
          bitField0_ |= 0x00000001;
          number_ = other.number_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        page.janardhan.labs.protos.Book.GenreNumber parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (page.janardhan.labs.protos.Book.GenreNumber) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object number_ = "";
      /**
       * <code>optional string number = 1;</code>
       * @return Whether the number field is set.
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string number = 1;</code>
       * @return The number.
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            number_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string number = 1;</code>
       * @return The bytes for number.
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string number = 1;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        number_ = getDefaultInstance().getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional string number = 1;</code>
       * @param value The bytes for number to set.
       * @return This builder for chaining.
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        number_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .labs.Book.GenreType type = 2 [default = FICTION];</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override public boolean hasType() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .labs.Book.GenreType type = 2 [default = FICTION];</code>
       * @return The type.
       */
      @java.lang.Override
      public page.janardhan.labs.protos.Book.GenreType getType() {
        @SuppressWarnings("deprecation")
        page.janardhan.labs.protos.Book.GenreType result = page.janardhan.labs.protos.Book.GenreType.valueOf(type_);
        return result == null ? page.janardhan.labs.protos.Book.GenreType.FICTION : result;
      }
      /**
       * <code>optional .labs.Book.GenreType type = 2 [default = FICTION];</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(page.janardhan.labs.protos.Book.GenreType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .labs.Book.GenreType type = 2 [default = FICTION];</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:labs.Book.GenreNumber)
    }

    // @@protoc_insertion_point(class_scope:labs.Book.GenreNumber)
    private static final page.janardhan.labs.protos.Book.GenreNumber DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new page.janardhan.labs.protos.Book.GenreNumber();
    }

    public static page.janardhan.labs.protos.Book.GenreNumber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GenreNumber>
        PARSER = new com.google.protobuf.AbstractParser<GenreNumber>() {
      @java.lang.Override
      public GenreNumber parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GenreNumber(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GenreNumber> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenreNumber> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public page.janardhan.labs.protos.Book.GenreNumber getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 1;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 2;
  private int id_;
  /**
   * <code>optional int32 id = 2;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int32 id = 2;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int PRICE_FIELD_NUMBER = 3;
  private int price_;
  /**
   * <code>optional int32 price = 3;</code>
   * @return Whether the price field is set.
   */
  @java.lang.Override
  public boolean hasPrice() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 price = 3;</code>
   * @return The price.
   */
  @java.lang.Override
  public int getPrice() {
    return price_;
  }

  public static final int GENRES_FIELD_NUMBER = 4;
  private java.util.List<page.janardhan.labs.protos.Book.GenreNumber> genres_;
  /**
   * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
   */
  @java.lang.Override
  public java.util.List<page.janardhan.labs.protos.Book.GenreNumber> getGenresList() {
    return genres_;
  }
  /**
   * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends page.janardhan.labs.protos.Book.GenreNumberOrBuilder> 
      getGenresOrBuilderList() {
    return genres_;
  }
  /**
   * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
   */
  @java.lang.Override
  public int getGenresCount() {
    return genres_.size();
  }
  /**
   * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
   */
  @java.lang.Override
  public page.janardhan.labs.protos.Book.GenreNumber getGenres(int index) {
    return genres_.get(index);
  }
  /**
   * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
   */
  @java.lang.Override
  public page.janardhan.labs.protos.Book.GenreNumberOrBuilder getGenresOrBuilder(
      int index) {
    return genres_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, id_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, price_);
    }
    for (int i = 0; i < genres_.size(); i++) {
      output.writeMessage(4, genres_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, id_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, price_);
    }
    for (int i = 0; i < genres_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, genres_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof page.janardhan.labs.protos.Book)) {
      return super.equals(obj);
    }
    page.janardhan.labs.protos.Book other = (page.janardhan.labs.protos.Book) obj;

    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (getId()
          != other.getId()) return false;
    }
    if (hasPrice() != other.hasPrice()) return false;
    if (hasPrice()) {
      if (getPrice()
          != other.getPrice()) return false;
    }
    if (!getGenresList()
        .equals(other.getGenresList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
    }
    if (hasPrice()) {
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getPrice();
    }
    if (getGenresCount() > 0) {
      hash = (37 * hash) + GENRES_FIELD_NUMBER;
      hash = (53 * hash) + getGenresList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static page.janardhan.labs.protos.Book parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static page.janardhan.labs.protos.Book parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static page.janardhan.labs.protos.Book parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static page.janardhan.labs.protos.Book parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static page.janardhan.labs.protos.Book parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static page.janardhan.labs.protos.Book parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static page.janardhan.labs.protos.Book parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static page.janardhan.labs.protos.Book parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static page.janardhan.labs.protos.Book parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static page.janardhan.labs.protos.Book parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static page.janardhan.labs.protos.Book parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static page.janardhan.labs.protos.Book parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(page.janardhan.labs.protos.Book prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code labs.Book}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:labs.Book)
      page.janardhan.labs.protos.BookOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return page.janardhan.labs.protos.BookProtos.internal_static_labs_Book_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return page.janardhan.labs.protos.BookProtos.internal_static_labs_Book_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              page.janardhan.labs.protos.Book.class, page.janardhan.labs.protos.Book.Builder.class);
    }

    // Construct using page.janardhan.labs.protos.Book.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getGenresFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      price_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      if (genresBuilder_ == null) {
        genres_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        genresBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return page.janardhan.labs.protos.BookProtos.internal_static_labs_Book_descriptor;
    }

    @java.lang.Override
    public page.janardhan.labs.protos.Book getDefaultInstanceForType() {
      return page.janardhan.labs.protos.Book.getDefaultInstance();
    }

    @java.lang.Override
    public page.janardhan.labs.protos.Book build() {
      page.janardhan.labs.protos.Book result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public page.janardhan.labs.protos.Book buildPartial() {
      page.janardhan.labs.protos.Book result = new page.janardhan.labs.protos.Book(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.price_ = price_;
        to_bitField0_ |= 0x00000004;
      }
      if (genresBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          genres_ = java.util.Collections.unmodifiableList(genres_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.genres_ = genres_;
      } else {
        result.genres_ = genresBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof page.janardhan.labs.protos.Book) {
        return mergeFrom((page.janardhan.labs.protos.Book)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(page.janardhan.labs.protos.Book other) {
      if (other == page.janardhan.labs.protos.Book.getDefaultInstance()) return this;
      if (other.hasName()) {
        bitField0_ |= 0x00000001;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasPrice()) {
        setPrice(other.getPrice());
      }
      if (genresBuilder_ == null) {
        if (!other.genres_.isEmpty()) {
          if (genres_.isEmpty()) {
            genres_ = other.genres_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureGenresIsMutable();
            genres_.addAll(other.genres_);
          }
          onChanged();
        }
      } else {
        if (!other.genres_.isEmpty()) {
          if (genresBuilder_.isEmpty()) {
            genresBuilder_.dispose();
            genresBuilder_ = null;
            genres_ = other.genres_;
            bitField0_ = (bitField0_ & ~0x00000008);
            genresBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getGenresFieldBuilder() : null;
          } else {
            genresBuilder_.addAllMessages(other.genres_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      page.janardhan.labs.protos.Book parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (page.janardhan.labs.protos.Book) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }

    private int id_ ;
    /**
     * <code>optional int32 id = 2;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>optional int32 id = 2;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      bitField0_ |= 0x00000002;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      id_ = 0;
      onChanged();
      return this;
    }

    private int price_ ;
    /**
     * <code>optional int32 price = 3;</code>
     * @return Whether the price field is set.
     */
    @java.lang.Override
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 price = 3;</code>
     * @return The price.
     */
    @java.lang.Override
    public int getPrice() {
      return price_;
    }
    /**
     * <code>optional int32 price = 3;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(int value) {
      bitField0_ |= 0x00000004;
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 price = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      bitField0_ = (bitField0_ & ~0x00000004);
      price_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<page.janardhan.labs.protos.Book.GenreNumber> genres_ =
      java.util.Collections.emptyList();
    private void ensureGenresIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        genres_ = new java.util.ArrayList<page.janardhan.labs.protos.Book.GenreNumber>(genres_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        page.janardhan.labs.protos.Book.GenreNumber, page.janardhan.labs.protos.Book.GenreNumber.Builder, page.janardhan.labs.protos.Book.GenreNumberOrBuilder> genresBuilder_;

    /**
     * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
     */
    public java.util.List<page.janardhan.labs.protos.Book.GenreNumber> getGenresList() {
      if (genresBuilder_ == null) {
        return java.util.Collections.unmodifiableList(genres_);
      } else {
        return genresBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
     */
    public int getGenresCount() {
      if (genresBuilder_ == null) {
        return genres_.size();
      } else {
        return genresBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
     */
    public page.janardhan.labs.protos.Book.GenreNumber getGenres(int index) {
      if (genresBuilder_ == null) {
        return genres_.get(index);
      } else {
        return genresBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
     */
    public Builder setGenres(
        int index, page.janardhan.labs.protos.Book.GenreNumber value) {
      if (genresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGenresIsMutable();
        genres_.set(index, value);
        onChanged();
      } else {
        genresBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
     */
    public Builder setGenres(
        int index, page.janardhan.labs.protos.Book.GenreNumber.Builder builderForValue) {
      if (genresBuilder_ == null) {
        ensureGenresIsMutable();
        genres_.set(index, builderForValue.build());
        onChanged();
      } else {
        genresBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
     */
    public Builder addGenres(page.janardhan.labs.protos.Book.GenreNumber value) {
      if (genresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGenresIsMutable();
        genres_.add(value);
        onChanged();
      } else {
        genresBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
     */
    public Builder addGenres(
        int index, page.janardhan.labs.protos.Book.GenreNumber value) {
      if (genresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGenresIsMutable();
        genres_.add(index, value);
        onChanged();
      } else {
        genresBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
     */
    public Builder addGenres(
        page.janardhan.labs.protos.Book.GenreNumber.Builder builderForValue) {
      if (genresBuilder_ == null) {
        ensureGenresIsMutable();
        genres_.add(builderForValue.build());
        onChanged();
      } else {
        genresBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
     */
    public Builder addGenres(
        int index, page.janardhan.labs.protos.Book.GenreNumber.Builder builderForValue) {
      if (genresBuilder_ == null) {
        ensureGenresIsMutable();
        genres_.add(index, builderForValue.build());
        onChanged();
      } else {
        genresBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
     */
    public Builder addAllGenres(
        java.lang.Iterable<? extends page.janardhan.labs.protos.Book.GenreNumber> values) {
      if (genresBuilder_ == null) {
        ensureGenresIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, genres_);
        onChanged();
      } else {
        genresBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
     */
    public Builder clearGenres() {
      if (genresBuilder_ == null) {
        genres_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        genresBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
     */
    public Builder removeGenres(int index) {
      if (genresBuilder_ == null) {
        ensureGenresIsMutable();
        genres_.remove(index);
        onChanged();
      } else {
        genresBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
     */
    public page.janardhan.labs.protos.Book.GenreNumber.Builder getGenresBuilder(
        int index) {
      return getGenresFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
     */
    public page.janardhan.labs.protos.Book.GenreNumberOrBuilder getGenresOrBuilder(
        int index) {
      if (genresBuilder_ == null) {
        return genres_.get(index);  } else {
        return genresBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
     */
    public java.util.List<? extends page.janardhan.labs.protos.Book.GenreNumberOrBuilder> 
         getGenresOrBuilderList() {
      if (genresBuilder_ != null) {
        return genresBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(genres_);
      }
    }
    /**
     * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
     */
    public page.janardhan.labs.protos.Book.GenreNumber.Builder addGenresBuilder() {
      return getGenresFieldBuilder().addBuilder(
          page.janardhan.labs.protos.Book.GenreNumber.getDefaultInstance());
    }
    /**
     * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
     */
    public page.janardhan.labs.protos.Book.GenreNumber.Builder addGenresBuilder(
        int index) {
      return getGenresFieldBuilder().addBuilder(
          index, page.janardhan.labs.protos.Book.GenreNumber.getDefaultInstance());
    }
    /**
     * <code>repeated .labs.Book.GenreNumber genres = 4;</code>
     */
    public java.util.List<page.janardhan.labs.protos.Book.GenreNumber.Builder> 
         getGenresBuilderList() {
      return getGenresFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        page.janardhan.labs.protos.Book.GenreNumber, page.janardhan.labs.protos.Book.GenreNumber.Builder, page.janardhan.labs.protos.Book.GenreNumberOrBuilder> 
        getGenresFieldBuilder() {
      if (genresBuilder_ == null) {
        genresBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            page.janardhan.labs.protos.Book.GenreNumber, page.janardhan.labs.protos.Book.GenreNumber.Builder, page.janardhan.labs.protos.Book.GenreNumberOrBuilder>(
                genres_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        genres_ = null;
      }
      return genresBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:labs.Book)
  }

  // @@protoc_insertion_point(class_scope:labs.Book)
  private static final page.janardhan.labs.protos.Book DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new page.janardhan.labs.protos.Book();
  }

  public static page.janardhan.labs.protos.Book getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Book>
      PARSER = new com.google.protobuf.AbstractParser<Book>() {
    @java.lang.Override
    public Book parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Book(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Book> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Book> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public page.janardhan.labs.protos.Book getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

