// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book.proto

package page.janardhan.labs.protos;

public interface LibraryBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:labs.LibraryBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .labs.Book books = 1;</code>
   */
  java.util.List<page.janardhan.labs.protos.Book> 
      getBooksList();
  /**
   * <code>repeated .labs.Book books = 1;</code>
   */
  page.janardhan.labs.protos.Book getBooks(int index);
  /**
   * <code>repeated .labs.Book books = 1;</code>
   */
  int getBooksCount();
  /**
   * <code>repeated .labs.Book books = 1;</code>
   */
  java.util.List<? extends page.janardhan.labs.protos.BookOrBuilder> 
      getBooksOrBuilderList();
  /**
   * <code>repeated .labs.Book books = 1;</code>
   */
  page.janardhan.labs.protos.BookOrBuilder getBooksOrBuilder(
      int index);
}
