// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book.proto

package page.janardhan.labs.protos;

/**
 * Protobuf type {@code labs.LibraryBook}
 */
public final class LibraryBook extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:labs.LibraryBook)
    LibraryBookOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LibraryBook.newBuilder() to construct.
  private LibraryBook(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LibraryBook() {
    books_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LibraryBook();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LibraryBook(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              books_ = new java.util.ArrayList<page.janardhan.labs.protos.Book>();
              mutable_bitField0_ |= 0x00000001;
            }
            books_.add(
                input.readMessage(page.janardhan.labs.protos.Book.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        books_ = java.util.Collections.unmodifiableList(books_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return page.janardhan.labs.protos.BookProtos.internal_static_labs_LibraryBook_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return page.janardhan.labs.protos.BookProtos.internal_static_labs_LibraryBook_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            page.janardhan.labs.protos.LibraryBook.class, page.janardhan.labs.protos.LibraryBook.Builder.class);
  }

  public static final int BOOKS_FIELD_NUMBER = 1;
  private java.util.List<page.janardhan.labs.protos.Book> books_;
  /**
   * <code>repeated .labs.Book books = 1;</code>
   */
  @java.lang.Override
  public java.util.List<page.janardhan.labs.protos.Book> getBooksList() {
    return books_;
  }
  /**
   * <code>repeated .labs.Book books = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends page.janardhan.labs.protos.BookOrBuilder> 
      getBooksOrBuilderList() {
    return books_;
  }
  /**
   * <code>repeated .labs.Book books = 1;</code>
   */
  @java.lang.Override
  public int getBooksCount() {
    return books_.size();
  }
  /**
   * <code>repeated .labs.Book books = 1;</code>
   */
  @java.lang.Override
  public page.janardhan.labs.protos.Book getBooks(int index) {
    return books_.get(index);
  }
  /**
   * <code>repeated .labs.Book books = 1;</code>
   */
  @java.lang.Override
  public page.janardhan.labs.protos.BookOrBuilder getBooksOrBuilder(
      int index) {
    return books_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < books_.size(); i++) {
      output.writeMessage(1, books_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < books_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, books_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof page.janardhan.labs.protos.LibraryBook)) {
      return super.equals(obj);
    }
    page.janardhan.labs.protos.LibraryBook other = (page.janardhan.labs.protos.LibraryBook) obj;

    if (!getBooksList()
        .equals(other.getBooksList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBooksCount() > 0) {
      hash = (37 * hash) + BOOKS_FIELD_NUMBER;
      hash = (53 * hash) + getBooksList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static page.janardhan.labs.protos.LibraryBook parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static page.janardhan.labs.protos.LibraryBook parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static page.janardhan.labs.protos.LibraryBook parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static page.janardhan.labs.protos.LibraryBook parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static page.janardhan.labs.protos.LibraryBook parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static page.janardhan.labs.protos.LibraryBook parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static page.janardhan.labs.protos.LibraryBook parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static page.janardhan.labs.protos.LibraryBook parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static page.janardhan.labs.protos.LibraryBook parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static page.janardhan.labs.protos.LibraryBook parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static page.janardhan.labs.protos.LibraryBook parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static page.janardhan.labs.protos.LibraryBook parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(page.janardhan.labs.protos.LibraryBook prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code labs.LibraryBook}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:labs.LibraryBook)
      page.janardhan.labs.protos.LibraryBookOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return page.janardhan.labs.protos.BookProtos.internal_static_labs_LibraryBook_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return page.janardhan.labs.protos.BookProtos.internal_static_labs_LibraryBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              page.janardhan.labs.protos.LibraryBook.class, page.janardhan.labs.protos.LibraryBook.Builder.class);
    }

    // Construct using page.janardhan.labs.protos.LibraryBook.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBooksFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (booksBuilder_ == null) {
        books_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        booksBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return page.janardhan.labs.protos.BookProtos.internal_static_labs_LibraryBook_descriptor;
    }

    @java.lang.Override
    public page.janardhan.labs.protos.LibraryBook getDefaultInstanceForType() {
      return page.janardhan.labs.protos.LibraryBook.getDefaultInstance();
    }

    @java.lang.Override
    public page.janardhan.labs.protos.LibraryBook build() {
      page.janardhan.labs.protos.LibraryBook result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public page.janardhan.labs.protos.LibraryBook buildPartial() {
      page.janardhan.labs.protos.LibraryBook result = new page.janardhan.labs.protos.LibraryBook(this);
      int from_bitField0_ = bitField0_;
      if (booksBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          books_ = java.util.Collections.unmodifiableList(books_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.books_ = books_;
      } else {
        result.books_ = booksBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof page.janardhan.labs.protos.LibraryBook) {
        return mergeFrom((page.janardhan.labs.protos.LibraryBook)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(page.janardhan.labs.protos.LibraryBook other) {
      if (other == page.janardhan.labs.protos.LibraryBook.getDefaultInstance()) return this;
      if (booksBuilder_ == null) {
        if (!other.books_.isEmpty()) {
          if (books_.isEmpty()) {
            books_ = other.books_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBooksIsMutable();
            books_.addAll(other.books_);
          }
          onChanged();
        }
      } else {
        if (!other.books_.isEmpty()) {
          if (booksBuilder_.isEmpty()) {
            booksBuilder_.dispose();
            booksBuilder_ = null;
            books_ = other.books_;
            bitField0_ = (bitField0_ & ~0x00000001);
            booksBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBooksFieldBuilder() : null;
          } else {
            booksBuilder_.addAllMessages(other.books_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      page.janardhan.labs.protos.LibraryBook parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (page.janardhan.labs.protos.LibraryBook) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<page.janardhan.labs.protos.Book> books_ =
      java.util.Collections.emptyList();
    private void ensureBooksIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        books_ = new java.util.ArrayList<page.janardhan.labs.protos.Book>(books_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        page.janardhan.labs.protos.Book, page.janardhan.labs.protos.Book.Builder, page.janardhan.labs.protos.BookOrBuilder> booksBuilder_;

    /**
     * <code>repeated .labs.Book books = 1;</code>
     */
    public java.util.List<page.janardhan.labs.protos.Book> getBooksList() {
      if (booksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(books_);
      } else {
        return booksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .labs.Book books = 1;</code>
     */
    public int getBooksCount() {
      if (booksBuilder_ == null) {
        return books_.size();
      } else {
        return booksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .labs.Book books = 1;</code>
     */
    public page.janardhan.labs.protos.Book getBooks(int index) {
      if (booksBuilder_ == null) {
        return books_.get(index);
      } else {
        return booksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .labs.Book books = 1;</code>
     */
    public Builder setBooks(
        int index, page.janardhan.labs.protos.Book value) {
      if (booksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBooksIsMutable();
        books_.set(index, value);
        onChanged();
      } else {
        booksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .labs.Book books = 1;</code>
     */
    public Builder setBooks(
        int index, page.janardhan.labs.protos.Book.Builder builderForValue) {
      if (booksBuilder_ == null) {
        ensureBooksIsMutable();
        books_.set(index, builderForValue.build());
        onChanged();
      } else {
        booksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .labs.Book books = 1;</code>
     */
    public Builder addBooks(page.janardhan.labs.protos.Book value) {
      if (booksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBooksIsMutable();
        books_.add(value);
        onChanged();
      } else {
        booksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .labs.Book books = 1;</code>
     */
    public Builder addBooks(
        int index, page.janardhan.labs.protos.Book value) {
      if (booksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBooksIsMutable();
        books_.add(index, value);
        onChanged();
      } else {
        booksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .labs.Book books = 1;</code>
     */
    public Builder addBooks(
        page.janardhan.labs.protos.Book.Builder builderForValue) {
      if (booksBuilder_ == null) {
        ensureBooksIsMutable();
        books_.add(builderForValue.build());
        onChanged();
      } else {
        booksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .labs.Book books = 1;</code>
     */
    public Builder addBooks(
        int index, page.janardhan.labs.protos.Book.Builder builderForValue) {
      if (booksBuilder_ == null) {
        ensureBooksIsMutable();
        books_.add(index, builderForValue.build());
        onChanged();
      } else {
        booksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .labs.Book books = 1;</code>
     */
    public Builder addAllBooks(
        java.lang.Iterable<? extends page.janardhan.labs.protos.Book> values) {
      if (booksBuilder_ == null) {
        ensureBooksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, books_);
        onChanged();
      } else {
        booksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .labs.Book books = 1;</code>
     */
    public Builder clearBooks() {
      if (booksBuilder_ == null) {
        books_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        booksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .labs.Book books = 1;</code>
     */
    public Builder removeBooks(int index) {
      if (booksBuilder_ == null) {
        ensureBooksIsMutable();
        books_.remove(index);
        onChanged();
      } else {
        booksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .labs.Book books = 1;</code>
     */
    public page.janardhan.labs.protos.Book.Builder getBooksBuilder(
        int index) {
      return getBooksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .labs.Book books = 1;</code>
     */
    public page.janardhan.labs.protos.BookOrBuilder getBooksOrBuilder(
        int index) {
      if (booksBuilder_ == null) {
        return books_.get(index);  } else {
        return booksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .labs.Book books = 1;</code>
     */
    public java.util.List<? extends page.janardhan.labs.protos.BookOrBuilder> 
         getBooksOrBuilderList() {
      if (booksBuilder_ != null) {
        return booksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(books_);
      }
    }
    /**
     * <code>repeated .labs.Book books = 1;</code>
     */
    public page.janardhan.labs.protos.Book.Builder addBooksBuilder() {
      return getBooksFieldBuilder().addBuilder(
          page.janardhan.labs.protos.Book.getDefaultInstance());
    }
    /**
     * <code>repeated .labs.Book books = 1;</code>
     */
    public page.janardhan.labs.protos.Book.Builder addBooksBuilder(
        int index) {
      return getBooksFieldBuilder().addBuilder(
          index, page.janardhan.labs.protos.Book.getDefaultInstance());
    }
    /**
     * <code>repeated .labs.Book books = 1;</code>
     */
    public java.util.List<page.janardhan.labs.protos.Book.Builder> 
         getBooksBuilderList() {
      return getBooksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        page.janardhan.labs.protos.Book, page.janardhan.labs.protos.Book.Builder, page.janardhan.labs.protos.BookOrBuilder> 
        getBooksFieldBuilder() {
      if (booksBuilder_ == null) {
        booksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            page.janardhan.labs.protos.Book, page.janardhan.labs.protos.Book.Builder, page.janardhan.labs.protos.BookOrBuilder>(
                books_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        books_ = null;
      }
      return booksBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:labs.LibraryBook)
  }

  // @@protoc_insertion_point(class_scope:labs.LibraryBook)
  private static final page.janardhan.labs.protos.LibraryBook DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new page.janardhan.labs.protos.LibraryBook();
  }

  public static page.janardhan.labs.protos.LibraryBook getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<LibraryBook>
      PARSER = new com.google.protobuf.AbstractParser<LibraryBook>() {
    @java.lang.Override
    public LibraryBook parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LibraryBook(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LibraryBook> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LibraryBook> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public page.janardhan.labs.protos.LibraryBook getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

